### ISSUE TITLE
SDK - SvelteKit integration

### ISSUE THREAD

**Issue by hitaspdotnet** [Telegram-Mini-Apps/telegram-apps#212]
[SvelteKit](https://kit.svelte.dev/) is built on [Svelte](https://svelte.dev/), a UI framework that uses a compiler to let you write breathtakingly concise components that do minimal work in the browser, using languages you already know — HTML, CSS and JavaScript

**fast:**
Powered by [Svelte](https://svelte.dev/) and [Vite](https://vitejs.dev/), speed is baked into every crevice: fast setup, fast dev, fast builds, fast page loads, fast navigation. fastest choice for an TMA.

**fun:**
No more wasted days figuring out bundler configuration, routing, SSR, CSP, TypeScript, deployment settings and all the other boring stuff.

**flexible:**
SPA? MPA? SSR? SSG? Check. SvelteKit gives you the tools to succeed whatever it is you're building. And it runs wherever JavaScript does.

**Comment by heyqbnk** [comment]
Svelte seems good to me, but the problem is as long as I am the only one regular contributor, I need some time to dive a bit in Svelte. This would also be cool if we could find other developers with experience in Svelte to evaluate the implementation.

We will keep this issue opened not to lose it and return after some time

**Comment by svex99** [comment]
I'd be interested to help or contribute with a Svelte integration. I think that the target version should be Svelte 5 (unstable at the moment), that will be backward compatible with Svelte 4, allowing to use the library in both versions.

**Comment by ZerdoX-x** [comment]
I just have started development of TMA with sveltekit. We'll see how it goes. I am also interested in contributing and maintaining sveltekit integration

> Svelte seems good to me, but the problem is as long as I am the only one regular contributor, I need some time to dive a bit in Svelte

@heyqbnk you could reach me and we can work on this together :)

**Comment by ZerdoX-x** [comment]
Any ideas about routing?

**Comment by pantemon** [comment]
Yeah, I'm also down to contribute to the SvelteKit SDK.

**Comment by svex99** [comment]
@ZerdoX-x I have used SvelteKit native routing without issues. On firsts mini-apps releases (when they were called web apps) there were issues navigating, and I had to use `goto(...)`, but that is not longer the case.

**Comment by 0xAr0k** [comment]
how is it going with the svelteKit tma SDK? I'm down to contribute as well!

**Comment by heyqbnk** [comment]
Hey! I would like to ask you to pausethe process a bit as long as I am currently working on a new major version. It will be completed approximately in 1-2 weeks

**Comment by pantemon** [comment]
@heyqbnk let me know if there is any help needed

**Comment by heyqbnk** [comment]
Hey! I forgot to remember, that SDKv2 is [ready](https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/2-x). 

You can implement the SvelteKit integration using the [SDK for React](https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk-react/2-x) as a reference

**Comment by heyqbnk** [comment]
@telegram-apps/sdk-svelte has just released. Thank you for your time

https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk-svelte
