### ISSUE TITLE
[Bug]: web_app_switch_inline_query is not working on Telegram Desktop

### ISSUE THREAD

**Issue by g3-tin** [Telegram-Mini-Apps/telegram-apps#334]
### Telegram Application

Telegram for macOS

### Describe the Bug

```tsx
"use client";
import { Button, Heading } from "@radix-ui/themes";
import { postEvent } from "@tma.js/sdk";

export const TelegramTest = () => {
  return (
    <>
      <Heading>Telegram Test</Heading>

      <Button
        onClick={async () => {
          postEvent("web_app_switch_inline_query", {
            query: "test",
            chat_types: ["channels", "groups"],
          });
        }}
      >
        Open link
      </Button>
    </>
  );
};
```

Hi team,

Thank for very useful library. This helps us a lot.

We have a issue that calling `web_app_switch_inline_query` , nothing happens on Telegram Desktop app. However, it works normally on Telegram Web and Telegram Mobile App.

### To Reproduce

1. Open telegram App
2. Using the upper sample code
3. Click the Open link button
4. Nothing happens

### Expected Behavior

It should open `web_app_switch_inline_query` and we can choose chat to send the inline query.

**Comment by heyqbnk** [comment]
Will check it after the weekends. Seems like not SDK issue and will possibly be moved to [issues](https://github.com/Telegram-Mini-Apps/issues).

**Comment by heyqbnk** [comment]
Works fine for me. Tried this code:

```ts
import { postEvent } from '@/sdk';

postEvent('web_app_switch_inline_query', {
  query: 'test',
  chat_types: ['channels', 'groups'],
});
```

I am not sure, but try removing the `async` function modifier in Button's `onClick` property.

**Comment by heyqbnk** [comment]
Working fine for me. Probably, it was fixed on the Telegram side
