### ISSUE TITLE
[Feature]: retrieveLaunchParams return error, instead of throwing

### ISSUE THREAD

**Issue by Mergemat** [Telegram-Mini-Apps/telegram-apps#382]
### Is your feature request related to a problem? Please describe.

retrieveLaunchParams errors, breaking Next.js build process.

So in Next.js we should do this
```ts
let initData = "";
try {
  const { initDataRaw } = retrieveLaunchParams();
  initData = initDataRaw ?? "";
} catch {
    //
}
```
Approach above fixes the situation, but this is a lot of code for the data that we use very often.

### Describe the solution you'd like

Maybe it could return errors instead of throwing, so using a hook will look something like this?
```ts
const {launchParams, errors, isError} = useLaunchParams(true);

if (isError) {
  return <p>{JSON.stringify(errors)}</p>;
}
```

**Comment by Mergemat** [comment]
I see that errors array being created, but not returned. This feature was planned already?
https://github.com/Telegram-Mini-Apps/tma.js/blob/c50df6da158925897768dfa65347142cd1c0dcd3/packages/sdk/src/launch-params/retrieveLaunchParams.ts#L12

**Comment by heyqbnk** [comment]
Could you explain how does it break Next.js build process?

**Comment by heyqbnk** [comment]
You will never have launch parameters on the build stage. How do you expect it working properly?

**Comment by Mergemat** [comment]
> You will never have launch parameters on the build stage. How do you expect it working properly?

not throwing errors, just returning them

**Comment by Mergemat** [comment]
now i need to block the whole app on server (like you did in next-template), and render only on client. but what's the point in using Next.js when your whole app is now client side

**Comment by heyqbnk** [comment]
> but what's the point in using Next.js when your whole app is now client side

There is no point at all. Telegram Mini Apps ismostly a client side technology. You can use `useLaunchParams(true)` in case, you are using SSR.
