### ISSUE TITLE
Access the microphone in the webapp only once

### ISSUE THREAD

**Issue by amirfaramarzi** [Telegram-Mini-Apps/telegram-apps#390]
I have a web app and I need to access the user's microphone

I access the user's microphone by using navigator.mediaDevices.getUserMedia code, but unfortunately, because Telegram uses the Safari engine to run the webapp, every time the getUserMedia function is called, it asks the user to access the microphone again (for security reasons, Safari for each time Calling the getUserMedia function takes permission to access the microphone from the user.

Does anyone have a solution to get microphone access from the user just once?

**Comment by heyqbnk** [comment]
This is not a place for discussions. You can use https://t.me/devs for it.
