### ISSUE TITLE
[Bug]: sdk version after update to new package name is 7.2

### ISSUE THREAD

**Issue by kirill-dev-pro** [Telegram-Mini-Apps/telegram-apps#395]
### Telegram Application

Other

### Describe the Bug

I just updated sdk from `@tma.js/sdk` to new `@telegram-apps/sdk` version 1.0.1 and getting error
```
Error: Method "web_app_setup_swipe_behavior" is unsupported in Mini Apps version 7.2
```

### To Reproduce

1. npm i @telegram-apps/sdk
2. use `swipeDebaviour.disableVerticalSwipe()`
3. go to debug console

### Expected Behavior

No errors

**Comment by heyqbnk** [comment]
Your Telegram client is not supporting this feature. Consider updating or wait for a new client release

**Comment by kirill-dev-pro** [comment]
Thanks, I was actually using mocked environment in the ordinary browser, and copied it from here https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/environment 
Didn't looked what actual values are there
