### ISSUE TITLE
[Observation]: Audio autoplay on windows with telegram-web-app.js

### ISSUE THREAD

**Issue by snimshchikov** [Telegram-Mini-Apps/telegram-apps#396]
### Is your feature request related to a problem? Please describe.

I am currently working on some audio stuff inside webapp and noticed that removing telegram's script as recommended in tma docs leads to Audio and AudioContext failing to start (because they need user gesture). But when telegram-web-app.js is included, the problem is somehow gone

### Describe the solution you'd like

No solution, idk

### Describe alternatives you've considered

Including both tma.js and telegram-web-app.js

### Additional context

Tested only on windows and android, android app behaves the same with and without telegram-web-app.js

**Comment by heyqbnk** [comment]
This should have nothing to do with tma.js or Telegram SDK. This is a standard web mechanism preventing the application from doing what is unexpected. Well, it should not work anyways, so there is nothing to do here then
