### ISSUE TITLE
[Bug]: Trim viewport with menu button view

### ISSUE THREAD

**Issue by RealOFF** [Telegram-Mini-Apps/telegram-apps#415]
### Telegram Application

Telegram for Android

### Describe the Bug

When running my app that applies "@telegram-apps/react-router-integration@1.0.1" and "@telegram-apps/sdk-react@1.1.2" on Android using Manu Button, the viewport is cut off. If I add the "https://telegram.org/js/telegram-web-app.js" script to the page, the viewport behaves as it should. Do I understand correctly that there is some side-effect in this script that affects viewport, and this effect is not present in sdk?

### To Reproduce

1. Run telegram mini app from "Menu Button" using sdk npm package on Android without applying "https://telegram.org/js/telegram-web-app.js".
2. Look at the viewport display.

Actual behavior:
<img width="294" alt="Screenshot 2024-07-15 at 11 42 56" src="https://github.com/user-attachments/assets/9ea6156c-7ba9-4e47-8971-0ca4a0bb91ae">

### Expected Behavior

<img width="274" alt="Screenshot 2024-07-15 at 11 46 14" src="https://github.com/user-attachments/assets/56ad533c-9a97-40b3-9b1a-94f2f94a30cd">

**Comment by heyqbnk** [comment]
Check if this solution fits you:
https://github.com/Telegram-Mini-Apps/issues/issues/25
