### ISSUE TITLE
[Bug]:  `TypeError` - `window.TelegramGameProxy.receiveEvent` Undefined on iOS Safari when load page

### ISSUE THREAD

**Issue by stanleytakamatsu** [Telegram-Mini-Apps/telegram-apps#418]
### Telegram Application

Telegram for iOS

#### Description

A `TypeError` occurs when load page on iOS devices using Mobile Safari UI/WKWebView via `InlineKeyboard`. The error message indicates that `undefined is not an object (evaluating 'window.TelegramGameProxy.receiveEvent')`.

```
TypeError
undefined is not an object (evaluating 'window.TelegramGameProxy.receiveEvent')
```

#### Environment

- **User-Agent**: Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
- **Browser**: Mobile Safari UI/WKWebView
- **Device**: iPhone
- **OS**: iOS 17.5.1

#### @telegram-apps version

  ```json
  "@telegram-apps/sdk-react": "^1.1.1",
  ```

### To Reproduce

Steps to Reproduce
- Open Mobile Safari on an iPhone with iOS 17.5.1.
- Observe the error message in the console.

### Expected Behavior

The page should load without errors and the `window.TelegramGameProxy.receiveEvent` should be defined.

**Comment by heyqbnk** [comment]
To solve this problem, it is required to define any Mini Apps event listener. It works fine with Telegram SDK, as long as they do it automatically even before the page was loaded.

I will think about a better solution, but for now, you could try using this code and execute it as early as possible:
```ts
import { subscribe } from '@telegram-apps/sdk-react';

// Just this line of code. It creates an event listener doing nothing, but
// also defines the window.TelegramGameProxy.receiveEvent function.
subscribe(() => {});
```

Unfortunately, to emit an event, Telegram for iOS inserts a JS code like this:
```ts
window.TelegramGameProxy.receiveEvent('popup_closed', ...);
```

So, they don't even check if `window.TelegramGameProxy.receiveEvent` exists at all

**Comment by stanleytakamatsu** [comment]
@heyqbnk Thank you very much for the feedback, I will try this approach.

**Comment by atakansavas** [comment]
@stanleytakamatsu Is that fix works for you?  Im still having that issue
