### ISSUE TITLE
[Bug]: — window is not defined,— Unable to get first navigation entry.,— sessionStorage is not defined

### ISSUE THREAD

**Issue by Toamatvey** [Telegram-Mini-Apps/telegram-apps#419]
### Telegram Application

Telegram for iOS, Telegram for macOS

### Describe the Bug

I keep getting this error every time I open my application in Telegram through ngrok tunnel

 ⨯ Error: Unable to retrieve launch parameters from any known source. Perhaps, you have opened your app outside Telegram?

📖 Refer to docs for more information:
https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/environment

Collected errors:
— window is not defined,— Unable to get first navigation entry.,— sessionStorage is not defined
    at Home (page.tsx:14:95)
digest: "4150758483"
 GET / 500 in 1675ms

And also, for some reason eruda is not working either. I have used the package for my previous project and everything worked smoothly, but now, I can't seem to be get it going

### To Reproduce

I have just created a new next js project. So far, I have just set up my layout and home page. Here is the code:

```typescript
// Root Layout

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Game</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="//cdn.jsdelivr.net/npm/eruda"></script>
        <script>eruda.init()</script>
      </head>
      <body className={inter.className}>
        <TelegramSDKProvider>{children}</TelegramSDKProvider>
      </body>
    </html>
  );
}

// TelegramSDKProvider

"use client";

import { SDKProvider } from "@telegram-apps/sdk-react";

export default function TelegramSDKProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SDKProvider acceptCustomStyles debug>
      {children}
    </SDKProvider>
  );
}

// Home Page

"use client";

import { useLaunchParams } from "@telegram-apps/sdk-react";
import { useEffect } from "react";

export default function Home() {
  const initData = useLaunchParams().initDataRaw;

  useEffect(() => {
    if (initData) {
      console.log("initData", initData);
    }
  }, [initData]);

  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24 w-screen">
      <h2 className="text-center text-2xl font-bold">Game</h2>
    </main>
  );
}

```

### Expected Behavior

No errors and eruda icon appearing in the app

**Comment by Toamatvey** [comment]
Why does it need ssr: true if it is used in the client component?

**Comment by paulplnkv** [comment]
> Why does it need ssr: true if it is used in the client component?

Even components with 'use client' are pre-rendered on the server

**Comment by heyqbnk** [comment]
> Why does it need ssr: true if it is used in the client component?

Seems like it is not considered as a client one, as long as window is undefined

**Comment by paulplnkv** [comment]
> Why does it need ssr: true if it is used in the client component?

Even 'use client' components are being pre-rendered on server

**Comment by heyqbnk** [comment]
> tried:
> 
> > ```ts
> > const initData = useLaunchParams(true)?.initDataRaw;
> > ```
> 
> and still error to me, even:
> 
> ```
>  const launchParams = useLaunchParams(true)
>   const initData = useInitDataRaw(true)
> ```
> 
> <img alt="Ảnh màn hình 2024-08-22 lúc 11 12 59" width="323" src="https://private-user-images.githubusercontent.com/8202437/360283147-a69450af-ed83-4952-b61c-d46749b145e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzQ4NDEsIm5iZiI6MTcyNDMzNDU0MSwicGF0aCI6Ii84MjAyNDM3LzM2MDI4MzE0Ny1hNjk0NTBhZi1lZDgzLTQ5NTItYjYxYy1kNDY3NDliMTQ1ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMTM0OTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQzNzY3NDY1ZmJmMzMwNmMyNGRiNzFjZWM5NzI2NjA0Nzk2YmRlNDA0N2QzZDg0MmYzZWJiNjQxNWQzZjBhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TQ_2JIjwykAleRYGBdPqqW6Wc_NZHIL-133Uv9uUy00">

Open the application inside Telegram

**Comment by Mosquid** [comment]
Why was this closed? As long as you provide `mockTelegramEnv`, people should be able to use outside Telegram

**Comment by heyqbnk** [comment]
> Why was this closed? As long as you provide `mockTelegramEnv`, people should be able to use outside Telegram

You can use it if needed. But the main purpose of this function is to provide the environment for the development mode
