### ISSUE TITLE
[Bug]: Listening to button events does not work.

### ISSUE THREAD

**Issue by AarNtyon** [Telegram-Mini-Apps/telegram-apps#420]
### Telegram Application

Telegram Desktop

### Describe the Bug

When I use it like this in the Next.js project, the buttons can be displayed, but the click event does not trigger, and the console shows 'receiveEvent back_button_pressed undefined'. 

  const mainButton = useMainButton();

  useEffect(() => {
    mainButton.setText("Hello").enable().show();

    mainButton.on("click", () => {
      console.log("click");
    });
    console.log(mainButton);
  }, [mainButton]);

### Expected Behavior

I hope it can work properly

**Comment by heyqbnk** [comment]
`@telegram-apps/sdk` is not showing any logs like `receiveEvent` in the console. Telegram SDK does it. You must not use them in the same time
