### ISSUE TITLE
The disableVerticalSwipe method cannot be used

### ISSUE THREAD

**Issue by lowskii** [Telegram-Mini-Apps/telegram-apps#422]
### Telegram Application

Telegram for Android, Telegram for iOS, Telegram Desktop, Telegram Web A, Telegram Web K

### Describe the Bug

When I try to use the new disableVerticalSwipe method, I get an error

### To Reproduce

I have added a new method disableVerticalSwipe. But when I log into the web version of telegram in my mini application, I get an error: Changing swipes behavior is not supported in version 7.6.

### Expected Behavior

The mini application should not collapse when swiping vertically inside the application

**Comment by heyqbnk** [comment]
Telegram applications are not supporting this method still

**Comment by jwcheon** [comment]
Ah I was just looking for this thanks for the confirmation @heyqbnk
