### ISSUE TITLE
readTextFromClipboard  always return null

### ISSUE THREAD

**Issue by jcsunran** [Telegram-Mini-Apps/telegram-apps#427]
I want to know how to get the access to clipboard in telegram mini app.

Thanks!

**Comment by heyqbnk** [comment]
Available only for Telegram partners.

**Comment by Daniil-33** [comment]
Is this function still working for "Telegram partners" only?

**Comment by heyqbnk** [comment]
> Is this function still working for "Telegram partners" only?

Yes
