### ISSUE TITLE
[Feature]: add shareToStory

### ISSUE THREAD

**Issue by daniilshamraev** [Telegram-Mini-Apps/telegram-apps#432]
### Describe the solution you'd like

add shareToStory

**Comment by heyqbnk** [comment]
To be implemented in a new package major version. I am not sure there are clients supporting Mini Apps v7.8 now, so this method will not even work

**Comment by awerc** [comment]
My client supports v7.8, and I have already seen a mini apps that utilizes shareToStory feature. Therefore, it would be great to release it sooner, because I can't use it without downloading the native SDK along with @telegram-apps/sdk @heyqbnk 

<img width="185" alt="image" src="https://github.com/user-attachments/assets/2486b312-33bc-4be9-b8c9-b2e7dec496b6">

**Comment by agudulin** [comment]
@awerc here's how you can use it:

```
import { postEvent } from "@telegram-apps/sdk-react";

postEvent("web_app_share_to_story" as any, {
  media_url: 'image.png',
  text: text.slice(0, 2048),
  widget_link: {},
});
```

**Comment by XantreDev** [comment]
```ts
interface CreateParams<
  Params = never,
  VersionedParam extends UnionKeys<Params> = never,
> {
  params: Params;
  versionedParams: VersionedParam;
}
declare module "@telegram-apps/sdk" {
  interface MiniAppsMethods {
    web_app_share_to_story: CreateParams<WepAppShareStory>;
  }
}

type WepAppShareStory = {
  media_url: string;
  text?: string;
  widget_link?: {
    url: string;
    name?: string;
  };
}
```

**Comment by hieutvIcetea** [comment]
@agudulin To implement this do I need to do something to upgrade my client version? I'm using tma.js and it's still 7.6 so using your way wont even work

**Comment by hieutvIcetea** [comment]
> @awerc here's how you can use it:
> 
> ```
> import { postEvent } from "@telegram-apps/sdk-react";
> 
> postEvent("web_app_share_to_story" as any, {
>   media_url: 'image.png',
>   text: text.slice(0, 2048),
>   widget_link: {},
> });
> ```

This method is not working for me, the console don't throw any error just the post event. Is there something I need to do to make this work?

**Comment by heyqbnk** [comment]
Done:
- https://github.com/Telegram-Mini-Apps/telegram-apps/blob/master/packages/bridge/src/methods/types/methods.ts#L394
- https://docs.telegram-mini-apps.com/platform/methods#web-app-share-to-story

**Comment by vaughn-xyz** [comment]
> @awerc here's how you can use it:
> 
> ```
> import { postEvent } from "@telegram-apps/sdk-react";
> 
> postEvent("web_app_share_to_story" as any, {
>   media_url: 'image.png',
>   text: text.slice(0, 2048),
>   widget_link: {},
> });
> ```

This works for me, despite using the latest telegram client, this library says it is unavailable on my client yet this `postEvent` works fine

**Comment by Isaacava** [comment]
Anyone got html and JavaScript code for this? 

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Telegram Web App - Share to Story</title>
  <script src="https://telegram.org/js/telegram-web-app.js"></script>
  <style>
    body {
      font-family: Arial, sans-serif;
      text-align: center;
      padding: 20px;
    }
    button {
      padding: 10px 20px;
      font-size: 16px;
      background-color: #0088cc;
      color: white;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }
    button:hover {
      background-color: #005f8c;
    }
  </style>
</head>
<body>
  <h1>Share Story on Telegram</h1>
  <p>Click the button below to share a story with an image and link!</p>
  <button id="shareButton">Share Story</button>

  <script>
    const tg = window.Telegram.WebApp;

    document.getElementById("shareButton").addEventListener("click", () => {
      try {
        // Attempt to share a story if the method is supported
        tg.shareToStory({
          media_url: "https://docs.telegram-mini-apps.com/logo.db0268ac.png",
          text: "Welcome!",
          widget_link: {
            url: "https://example.com",
            name: "Visit Us",
          },
        });
      } catch (error) {
        console.error("Error while sharing the story:", error);
      }
    });

    // Expand the Web App for better user experience
    tg.expand();
  </script>
</body>
</html>

``` 
This one isn't working 
Can someone check the code? 
Thanks

**Comment by Isaacava** [comment]
> try to change...
> 
> tg.shareToStory( media_url: "https://docs.telegram-mini-apps.com/logo.db0268ac.png", { text: "Welcome!", widget_link: { url: "https://example.com", name: "Visit Us", } );

Change it to what 
Can you assist with the code 
Thanks

**Comment by AduraJohn** [comment]
Could anyone here help me please, after the user has shared the story to their status, what kind of automatic verification can be done to check if the user is actually honest (shared the story) with this task or not before being rewarded. Is it the bot that will perform the verification or what, I'm confused please!
