### ISSUE TITLE
 METHOD_INVALID Error when i call web_app_invoke_custom_method

### ISSUE THREAD

**Issue by vircs8** [Telegram-Mini-Apps/telegram-apps#433]
I am encountering an issue when trying to call the web_app_invoke_custom_method on my Telegram bot. The method returns a METHOD_INVALID error despite following the available documentation and examples.

**Comment by heyqbnk** [comment]
Any code sample?

**Comment by vircs8** [comment]
`let addCustomMethodInvokedEvent = false;
const customMethodCallbackMap = new Map();
const customMethodCallback = (res) => {
    if(customMethodCallbackMap.size > 0) {
        if(customMethodCallbackMap.has(res.req_id)) {
            const callback = customMethodCallbackMap.get(res.req_id);
            customMethodCallbackMap.delete(res.req_id);
            callback(res);
        }
    }
};
export function uInvokeCustomMethod(method, callback, params) {
    try {
        const id = uGenerateRandomString();

        if(addCustomMethodInvokedEvent === false) {
            addCustomMethodInvokedEvent = true;
            on("custom_method_invoked", customMethodCallback);
        }

        if(typeof callback === "function") {
            customMethodCallbackMap.set(id, callback);
        }
        postEvent("web_app_invoke_custom_method", {
            req_id: id,
            method,
            params: params || {},
        });
    } catch(e) {
        console.error(e);
    }
}

 uInvokeCustomMethod("invoke_custom_method", (res) => {
        console.log("invoke_custom_method", res);
    });`

**Comment by heyqbnk** [comment]
You are using it wrong. Use docs:
https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/methods-and-events#invoking-custom-methods
