### ISSUE TITLE
[Bug]: @telegram-apps/init-data-node with NextJS doesn't work

### ISSUE THREAD

**Issue by shazgames1** [Telegram-Mini-Apps/telegram-apps#437]
### Telegram Application

Telegram Desktop

### Describe the Bug

I try to use @telegram-apps/init-data-node's validate function on server, but get error. 

```
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

### To Reproduce

1. Create api route file with following content: 
```
import { validate } from "@telegram-apps/init-data-node"

export const GET = async () => {
  validate("", "")
}
```
2. Save and open the api route in browser
3. See error

### Expected Behavior

Successful compilation

**Comment by heyqbnk** [comment]
https://docs.telegram-mini-apps.com/packages/telegram-apps-init-data-node#web-crypto-api

**Comment by shazgames1** [comment]
Thanks! It works when I use the web directory of the module, but it's weird that it doesn't work without /web because I run the code on the server, in node.js
