### ISSUE TITLE
[Feature]: BoostChannel

### ISSUE THREAD

**Issue by feng-derivio** [Telegram-Mini-Apps/telegram-apps#438]
### Is your feature request related to a problem? Please describe.

I want to use this [ChannelBoost](https://core.telegram.org/api/boost#:~:text=Telegram%20Premium%20users%20can%20grant,more%20boosts%20by%20starting%20giveaways%20%C2%BB.) feature.

### Describe the solution you'd like

Include this feature in the library

### Describe alternatives you've considered

Show some example of how to boost a channel.

**Comment by heyqbnk** [comment]
There is no such functionality in Telegram Mini Apps. The SDK can't implement the functionality which doesn't exist, unfortunately.

**Comment by feng-derivio** [comment]
Thanks, it turns out everything in telegram is just a link. I found the correct info here:
https://programminginsider.com/what-is-telegram-boost-guide-to-enable-channel-stories/
