### ISSUE TITLE
[Bug]:  about openTelegramLink in setTimeout

### ISSUE THREAD

**Issue by cheerylong** [Telegram-Mini-Apps/telegram-apps#439]
### Telegram Application

Other

### Describe the Bug

Why does this piece of code work
`window?.Telegram?.WebApp?.openTelegramLink('https://t.me/mybot')`

 but this one doesn't?
`  
 setTimeout(() => {
     window?.Telegram?.WebApp?.openTelegramLink('https://t.me/mybot')
  }, 2000)
`

### To Reproduce

 setTimeout(() => {
     window?.Telegram?.WebApp?.openTelegramLink('https://t.me/mybot')
  }, 2000)

### Expected Behavior

This code is functioning properly.

**Comment by heyqbnk** [comment]
Ask in @devs chat. This issue is not about the package in the repo.
