### ISSUE TITLE
[Bug]: Hooks SSR error for client components

### ISSUE THREAD

**Issue by thecoorum** [Telegram-Mini-Apps/telegram-apps#440]
### Telegram Application

Telegram for macOS

### Describe the Bug

When using `@telegram-apps/sdk-react` in the client components it always logs the following error to the console

```
Error: Using hooks on the server side, you must explicitly specify ssr = true option
```

Is that expected behavior?

### To Reproduce

1. Using Next.js starter create a component/page/provider with `"use client"` directive at the top of the file
2. See an error

### Expected Behavior

I don't really know if that's an expected behavior or not

**Comment by heyqbnk** [comment]
I don't know how the next client components work. If you see this message, it means, the hook was called on the server side (where window is missing)

**Comment by json-jcc** [comment]
i also found this bug, i used these hooks with ssr=false in a next.js client component, reports this 'Using hooks on the server side, you must explicitly specify ssr = true option'

**Comment by heyqbnk** [comment]
Next.js client components may be rendered on the server side:
https://nextjs.org/docs/app/building-your-application/rendering/client-components#how-are-client-components-rendered
