### ISSUE TITLE
[Bug]: Issue crash android device

### ISSUE THREAD

**Issue by VanThuan76** [Telegram-Mini-Apps/telegram-apps#450]
### Telegram Application

Telegram for Android

### Describe the Bug

I've tried to follow the process to track down why my Android device is crashing when using the postEvent method, but I haven't been successful. I've also read the documentation on the official site. Could this issue be related to the version of the library or something else?

  ``` .ts
 try {
       postEvent && postEvent('web_app_set_header_color', { color: '#000' });
       postEvent && postEvent('web_app_expand');
       postEvent && postEvent('web_app_setup_swipe_behavior', { allow_vertical_swipe: false })
} catch (error) {
       console.log(error)
}
```

 **Is there an alternative solution?**

### To Reproduce

Open the app -> Black screen (unable to check error) -> The app crashes

### Expected Behavior

As described, I would like to use _web_app_set_header_color, web_app_expand, and web_app_setup_swipe_behavior_ through the postEvent method, which can be debugged more easily.

**Comment by heyqbnk** [comment]
You should check which call fails exactly. Well, for sure, the problem is not in the SDK. The problem is that Telegram for Android incorrectly processes called method leading to the application crash. I already saw this problem in Telegram Desktop
