### ISSUE TITLE
How to open tg://-like links

### ISSUE THREAD

**Issue by mikhaillav** [Telegram-Mini-Apps/telegram-apps#451]
I need to open links like `tg://user?id=12345678`. So for example by pressing a button you can open someones profile.

I tried to use `utils.openLink` and `openTelegramLink` (just in case). 
- With `openLink` mini app crashed and I don't know how to fetch any debug information in this case. 
- With `openTelegramLink` I got an error about using only `t.me` links (as expected).

Code to reproduce crash (assuming you have `<SDKProvider />`)

```tsx
// page.tsx
"use client";

import { initUtils } from "@telegram-apps/sdk-react";

function openUserProfile() {
	const utils = initUtils();

	utils.openLink("tg://user?id=12345678"); // put your own id here
}

export default function Home() {
	return (
		<button onClick={openUserProfile}>
			<p>Click me!</p>
		</button>
	);
}
```

I also used nextjs `<Link>` & `<a>` but they don't seem to be working (just nothing happens on click).

I ran out of ideas how to implement this feature, maybe this even a bug. Will appreciate any help.

**Comment by heyqbnk** [comment]
I am not sure, there is a way to open such kind of links. You could try opening them via usual way we use in browsers. In case, it works fine in all Telegram applications, we may add it in the SDK

**Comment by mikhaillav** [comment]
I tried to open it via browser. It asked me to open telegram but didn't open requested chat.
![image](https://github.com/user-attachments/assets/13c24428-2eb6-4356-bd12-60c7e65caee0)
Thats sad. But thank you for the response!

**Comment by mikhaillav** [comment]
Accroding to [documentation](https://core.telegram.org/api/links#id-links) _normal clients_ should ignore these links. Its telegram issue.
