### ISSUE TITLE
[Bug]: I have many renders

### ISSUE THREAD

**Issue by virus231** [Telegram-Mini-Apps/telegram-apps#453]
### Telegram Application

Telegram Web A, Telegram Web K

### Describe the Bug

I working with library **[nuqs](https://github.com/47ng/nuqs)**, and I got many renders, when I change state in nuqs
<img width="465" alt="image" src="https://github.com/user-attachments/assets/cc91e18e-0399-47d3-ba75-5a3c1e9706b7">
Page stopped

### To Reproduce
Click on a type salon, and click on a type master
<img width="394" alt="image" src="https://github.com/user-attachments/assets/ce6beed7-8161-45fb-a14b-1feb17ec9135">
<img width="409" alt="image" src="https://github.com/user-attachments/assets/afcdd90a-4b1f-465f-a5cf-98af8b198f0a">
<img width="465" alt="image" src="https://github.com/user-attachments/assets/cc91e18e-0399-47d3-ba75-5a3c1e9706b7">

### Expected Behavior

App is working, not many renders

**Comment by heyqbnk** [comment]
Not related to SDK.
