### ISSUE TITLE
[Bug]: useInitDataRaw return object instead Raw Data

### ISSUE THREAD

**Issue by belov38** [Telegram-Mini-Apps/telegram-apps#458]
### Telegram Application

Telegram for iOS, Telegram Desktop, Other

### Describe the Bug

useInitDataRaw() return object instead raw data

### To Reproduce

```
import { useInitDataRaw } from '@telegram-apps/sdk-react';
...
const initDataRaw = useInitDataRaw ()
```

### Expected Behavior

expect  initDataRaw  is string, but got Object

**Comment by heyqbnk** [comment]
Yes, that's right. I assume, its name may be misleading. To get the result you expect, consider using such code:

```
useLaunchParams().initDataRaw
```
