### ISSUE TITLE
[Bug]: down image not working

### ISSUE THREAD

**Issue by flamingooo7** [Telegram-Mini-Apps/telegram-apps#460]
### Telegram Application

Telegram for Android

### Describe the Bug

In my miniapp, i try  implement the image download feature, but it is not working.
link this: <a href='https://xxx.png' download='demo.png' >download</a>

### Expected Behavior

working normally

**Comment by heyqbnk** [comment]
Not related to SDK or any other component. 

Consider creating an issue in the [issues](https://github.com/telegram-mini-apps/issues) repository. 

You can use navigator.share where supported, or send the file using the bot. It is the only way I know

**Comment by heyqbnk** [comment]
It is already supported in v8.0

**Comment by LyoSU** [comment]
> > > Вона вже підтримується у версії 8.0
> > 
> > 
> > На жаль, не можу знайти. Чи можете ви надіслати мені посилання на документ? Дякую!
> 
> https://core.telegram.org/bots/webapps#november-17-2024

How to call it using sdk?

**Comment by LyoSU** [comment]
> > > It is already supported in v8.0
> > 
> > 
> > Unfortunately I can't find it. Can you send me a link to the document? Thanks!
> 
> https://core.telegram.org/bots/webapps#november-17-2024

How to call it using sdk?
