### ISSUE TITLE
[Bug]: Timeout reached: 1000ms

### ISSUE THREAD

**Issue by lxiiiixi** [Telegram-Mini-Apps/telegram-apps#462]
### Telegram Application

Telegram for Android

### Describe the Bug

This error occurs as soon as I open the Telegram mini app. And some people frequently encounter this error, while others have never experienced it.

### To Reproduce

As soon as I open the Telegram mini app

### Expected Behavior

I don't know why this error occurs; I didn't expect it to happen.

**Comment by heyqbnk** [comment]
Yesterday I also heard about this problem on Android. I assume, Telegram team released an update which broke some of the TMA functionality in Android. 

Which version of the package do you use?

**Comment by lxiiiixi** [comment]
I am using version ^1.0.0 of @telegram-apps/sdk-react, and my Telegram version is Android v11.0.1 (5176), with the tgWebAppVersion parameter set at 7.8.

**Comment by heyqbnk** [comment]
A possible reason could be the Telegram application not responding to the `viewport_changed` event. Could you try commenting all code connected with `useViewport`and try again? Also check if you are not using the current SDK along with the Telegram SDK

**Comment by lxiiiixi** [comment]
> A possible reason could be the Telegram application not responding to the `viewport_changed` event. Could you try commenting all code connected with `useViewport`and try again? Also check if you are not using the current SDK along with the Telegram SDK

I removed the features related to useViewport, and the problem hasn't occurred again. Thank you, at least this can temporarily solve my issue.

**Comment by heyqbnk** [comment]
We should wait for Telegram to fix their own bug, unfortunately
