### ISSUE TITLE
[Feature]: I want to know how to set this built-in browser to landscape mode.

### ISSUE THREAD

**Issue by simerlin** [Telegram-Mini-Apps/telegram-apps#463]
### Is your feature request related to a problem? Please describe.

Our game is designed for landscape mode, but currently, all the windows that are opening are in portrait mode
![image](https://github.com/user-attachments/assets/67e2369b-fd3a-4adf-a99e-7945e82a2513)

### Describe the solution you'd like

When will landscape mode be supported, or can you tell me how to set it to landscape mode?

**Comment by heyqbnk** [comment]
You can't set it to landscape mode in desktop versions of Telegram (at least in Telegram Desktop). I have no information if it will ever be supported
