### ISSUE TITLE
[Feature]: Telegram Mini Design

### ISSUE THREAD

**Issue by thewykittens** [Telegram-Mini-Apps/telegram-apps#464]
### Is your feature request related to a problem? Please describe.

You have to go somewhere else, other than Telegram, do a bunch of work, import and add the app, wa-la, you've wasted all your time on that mini-app.

### Describe the solution you'd like

Make a mini app on Telegram, do all of it on Telegram.

### Describe alternatives you've considered

Other Solutions:
Make a free bot for making mini-apps

### Additional context

No Additional Context

**Comment by thewykittens** [comment]
You're Welcome for this Issue.

**Comment by thewykittens** [comment]
Sorry, just checking out the closed feature of GitHub.

**Comment by heyqbnk** [comment]
Not related to any products in the repository. You can discuss your feature in the [@devs](https://t.me/devs) chat.
