### ISSUE TITLE
[Feature]: App Jams, Event, and Collections

### ISSUE THREAD

**Issue by thewykittens** [Telegram-Mini-Apps/telegram-apps#465]
### Is your feature request related to a problem? Please describe.

No way to add a collection or event of apps to Telegram.

### Describe the solution you'd like

Add the feature to add events, collections, and more stuff like that.

### Describe alternatives you've considered

No Alternatives.

### Additional context

No Additional Context.

**Comment by heyqbnk** [comment]
To collect events, you should use some 3-rd party services like Mixpanel or Google Analytics. The SDK has quite narrow purpose - provide basic functionality related to Telegram Mini Apps
