### ISSUE TITLE
[Bug]: An error occurred processing the "theme_changed" event from the Telegram application.

### ISSUE THREAD

**Issue by LWJerri** [Telegram-Mini-Apps/telegram-apps#466]
### Telegram Application

Telegram for Android

### Describe the Bug

![image](https://github.com/user-attachments/assets/fb34b8f0-584f-4907-9c0f-7083f861d721)

I choose Telegram for Andoird because Sentry fixed this error exactly in the Android client. To be honest, out of a thousand times I've opened the app, this error has only appeared 5 times, but it's still annoying. I have contacted people who had this error and they have regular clients, nothing modified.

### To Reproduce

1. Just use Telegram application and with some chance you will get this error.

### Expected Behavior

Correct handling of the user theme without error.

**Comment by heyqbnk** [comment]
I am not sure, we will do something with this. Telegram documentation describes this event having values as RGB strings like "#AABBCC". For some reason, the Android client decided to send some negative numbers. 

This error may be temporary, so it is better not to pay attention to it. Especially, when only 5 users had it.

I can also add, that this will not work with the Telegram SDK. Knowing, that the Telegram SDK is not checking events' payloads data, I wonder what will happen in the application with such an event

**Comment by LWJerri** [comment]
@heyqbnk, just checked `tgWebAppThemeParams` with whom the error occurred and the values look like this:

```txt
URLSearchParams {
  '/#tgWebAppData' => 'query_id=AAFll6ogAAAAAGWXqiB5iXZz&user=%7B%22id%22%3A545130789%2C%22first_name%22%3A%22first_name%22%2C%22last_name%22%3A%22%22%2C%22username%22%3A%22username%22%2C%22language_code%22%3A%22uk%22%2C%22allows_write_to_pm%22%3Atrue%7D&auth_date=date&hash=hash',
  'tgWebAppVersion' => '7.8',
  'tgWebAppPlatform' => 'android',
  'tgWebAppThemeParams' => '{"bg_color":"#212d3b","section_bg_color":"#1d2733","secondary_bg_color":"#151e27","text_color":"#ffffff","hint_color":"#7d8b99","link_color":"#5eabe1","button_color":"#50a8eb","button_text_color":"#ffffff","header_bg_color":"#242d39","accent_text_color":"#64b5ef","section_header_text_color":"#79c4fc","subtitle_text_color":"#7b8790","destructive_text_color":"#ee686f","section_separator_color":"#0d1218"}' }
```

So it's mean coming data from Telegram is correct, isn't it?

**Comment by heyqbnk** [comment]
Which version of the SDK is that? I don't see a custom parser for this event. It should be [here](https://github.com/Telegram-Mini-Apps/telegram-apps/blob/master/packages/sdk/src/bridge/events/event-emitter/createMiniAppsEventEmitter.ts#L23).

According to [this](https://github.com/Telegram-Mini-Apps/telegram-apps/blob/master/packages/sdk/src/bridge/events/event-emitter/createMiniAppsEventEmitter.ts#L123-L132) code, the problem could be some event listener throwing an error

**Comment by LWJerri** [comment]
> You are sending launch parameters. The problem is not in them. The problem is in the `theme_changed` event payload.
> 
> Which version of the SDK is that? I don't see a custom parser for this event. It should be [here](https://github.com/Telegram-Mini-Apps/telegram-apps/blob/master/packages/sdk/src/bridge/events/event-emitter/createMiniAppsEventEmitter.ts#L23).
> 
> According to [this](https://github.com/Telegram-Mini-Apps/telegram-apps/blob/master/packages/sdk/src/bridge/events/event-emitter/createMiniAppsEventEmitter.ts#L123-L132) code, the problem could be some event listener throwing an error

Yeah, you're right. I was thinking that maybe the original data is being transferred somehow wrong, because this error occurs just after the application is started.
