### ISSUE TITLE
[Feature]: Is any ways to only open a single mini app?

### ISSUE THREAD

**Issue by EF09FE** [Telegram-Mini-Apps/telegram-apps#469]
### Is your feature request related to a problem? Please describe.

When I open mini app from link, click 3 times link,  it will open 3 same mini apps, is there any ways to just open 1 mini app?

As you can see, there has 4 Wallet apps are opened, but I just need one, maybe I need redirect frequently between connected website and Wallet app, there will open many duplicate Wallet apps, it is not a good user experience

![image](https://github.com/user-attachments/assets/741c0235-8edc-441b-a5b1-cd479f79a903)

### Describe the solution you'd like

No matter how many times I open mini app, if there have a mini app is opened, just reuse the opened mini app, NOT open new same mini app

**Comment by heyqbnk** [comment]
Can't be handled on the SDK side. Sounds more like a suggestion to Telegram
