### ISSUE TITLE
[Feature]: add setHeaderTextColor to `miniApp`

### ISSUE THREAD

**Issue by web3jt** [Telegram-Mini-Apps/telegram-apps#470]
### Is your feature request related to a problem? Please describe.

```typescript
  useEffect(() => {
    if (!miniApp || !theme) return;

    miniApp.setBgColor(theme === 'dark' ? '#18181b' : '#f4f4f5');
    miniApp.setHeaderColor('#18181b');
    /**
     * @TODO set header text color
     */
    // miniApp.setHeaderTextColor('#f4f4f5'); // section_header_text_color
  }, [
    miniApp,
    theme,
  ]);
```

I couldn't `miniApp.setHeaderTextColor(` above there.

Plz support `section_header_text_color` of [Bot API 7.0 @December 29, 2023](https://core.telegram.org/bots/webapps#december-29-2023)

### Describe the solution you'd like

both for `@telegram-apps/sdk-react` and `@telegram-apps/sdk`

and I think there are more features about the MiniApp theme are supposed to be supported such as `section_header_text_color`, `section_separator_color`, `subtitle_text_color` and `destructive_text_color` etc...

### Describe alternatives you've considered

N/A

### Additional context

super thanks

**Comment by web3jt** [comment]
I found `useThemeParams` but could just get `sectionHeaderTextColor` there

**Comment by heyqbnk** [comment]
There is no way to implement such a functionality because the platform does not provide a corresponding method

**Comment by web3jt** [comment]
tks for ur reply

something I found in their docs:

for `section_header_text_color` in [ThemeParams](https://core.telegram.org/bots/webapps#themeparams)

> Optional. Bot API 7.0+ Header text color for the section in the #RRGGBB format.
Also available as the CSS variable var(--tg-theme-section-header-text-color).

so it is only possible to get but cannot set/change it?

**Comment by web3jt** [comment]
and I cannot even find the method `showAlert` in `sdk-react`, is that possible?

**Comment by heyqbnk** [comment]
> so it is only possible to get but cannot set/change it?

Yes, you can't change it.

`showAlert` is the method from the Telegram SDK. Internally, it just uses the Telegram SDK `openPopup` method, so you can implement the same using `@telegram-apps/sdk`
