### ISSUE TITLE
[Question] How to maintain user session in telegram mini apps?

### ISSUE THREAD

**Issue by yalamber** [Telegram-Mini-Apps/telegram-apps#471]
Hello, 
I am trying to set session once users load the mini apps so that future api request can use that session. I tried to use session cookie but it seems like cookies are dropped in the requests and I cannot set session cookies for the app. Do I need to always validate initData for each api reqeust to maintain the session?

**Comment by heyqbnk** [comment]
> Do I need to always validate initData for each api reqeust to maintain the session?

Yes, you do. [Here](https://docs.telegram-mini-apps.com/platform/init-data#authorization-and-authentication) is more information about it
