### ISSUE TITLE
Checking if Invoice is paid

### ISSUE THREAD

**Issue by yalamber** [Telegram-Mini-Apps/telegram-apps#474]
Hello, 
I am using https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/components/invoice to open the invoice link in my mini app. After the payment is successful, I want to make an api request to the server, How do we make sure invoice is paid on the server side?

**Comment by heyqbnk** [comment]
I assume, you should receive an [Update](https://core.telegram.org/bots/api#update), containing the payment information
