### ISSUE TITLE
[Bug]: Documentation for SDK-React is completely missing (404)

### ISSUE THREAD

**Issue by vaughn-xyz** [Telegram-Mini-Apps/telegram-apps#486]
### Telegram Application

Other

### Describe the Bug

https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk-react

### To Reproduce

1. Go to https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk-react
2. Verify 404

### Expected Behavior

1. Go to https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk-react
2. View documentation for using v2

**Comment by heyqbnk** [comment]
https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk-react/1-x
