### ISSUE TITLE
why laravel blade file cannot receive start_param value

### ISSUE THREAD

**Issue by vnxz** [Telegram-Mini-Apps/telegram-apps#495]
I tried to get referral id from start_param but always empty value.
why ?
i enter the min app via referral link 
https://t.me/neolaunchBot?start=startapp=56789999

and try to get referral id from laravel blade file but never receive.

does start_param only has value in react components?
why not work in laravel blade file javascript

`<script>
document.addEventListener('DOMContentLoaded', function () {
  const WebApp = window.Telegram.WebApp;

  // Wait for WebApp to be ready
  WebApp.ready();

  // Get the URL parameter 'tgWebAppStartParam' if available
  const urlParams = new URLSearchParams(window.location.search);
  const tgWebAppStartParam = urlParams.get('tgWebAppStartParam');
    
  // Use either tgWebAppStartParam or start_param from initDataUnsafe
  const startParam = WebApp.initDataUnsafe ? WebApp.initDataUnsafe.start_param : null;
  const referralID = tgWebAppStartParam || startParam;

  // Retrieve the user ID from initDataUnsafe
  const userId = WebApp.initDataUnsafe.user?.id || '';

  // Display the referral ID and user ID in the HTML
  document.getElementById('refId').textContent = referralID;
  document.getElementById('userId').textContent = userId;

  // Log the values for debugging
  console.log("Referral Start Param: ", startParam);
  console.log("User ID: ", userId);
});
</script> `

**Comment by heyqbnk** [comment]
This repository is not related to the Telegram SDK. 

Consider using the official documentation:

https://core.telegram.org/bots/webapps
