### ISSUE TITLE
[Bug]: iOS Scroll Bug: Page Bottom Lifts on Upward Scroll

### ISSUE THREAD

**Issue by kisaragi99** [Telegram-Mini-Apps/telegram-apps#499]
### Telegram Application

Telegram for iOS

### Describe the Bug

When we do upward scroll (pull) we reach the bottom of the page and the bottom of the page lifts as well.

Devices tested:
- Iphone 15pro - BUG
- Iphone 13 - BUG
- Iphone 7 - NO BUG
- Android Phone - NO BUG

* Videos from Iphone 15pro

https://github.com/user-attachments/assets/e7063ee3-e5f7-421c-aeb5-a4e7cdc93fc8

https://github.com/user-attachments/assets/70b233a3-6e36-446f-904e-b86d46dd057a

Used this to change background color on the video:
postEvent('web_app_set_background_color', { color: '#53FF73' });

https://github.com/user-attachments/assets/db28f348-e817-4a62-904b-9da4eb5803f7

### To Reproduce

repo: https://github.com/Telegram-Mini-Apps/reactjs-template

1) Install and run this template.
2) Try to do upward scroll (pull your finger from bottom to the top)

### Expected Behavior

Bottom of the page should not be lifted.

**Comment by heyqbnk** [comment]
The problem is not in the template nor in the SDK. It is the intended behavior implemented by the Telegram developers.

The other question is "why?"

**Comment by kisaragi99** [comment]
Thank you for clarification. If it is intended - I do not have any questions.

- "why?"
- because it seemed like a bug to me cuz I dont have this behaviour on older iphones and on android.

**Comment by heyqbnk** [comment]
The reason can possible be a different Telegram client version on the older devices.

Maybe it is somehow related to the newer iOS versions. I don't really know. Will be looking for solutions the next month

**Comment by linxuanweb** [comment]
Hi, I noticed that I’m experiencing a similar issue where all my full-screen, non-sliding pop-up windows have become slidable, which is affecting the user experience quite significantly.

I came across your comment, and I was wondering if you’ve found any solution or workaround for this problem? Any advice would be greatly appreciated. Thank you in advance for your time and help!

**Comment by kisaragi99** [comment]
> Hi, I noticed that I’m experiencing a similar issue where all my full-screen, non-sliding pop-up windows have become slidable, which is affecting the user experience quite significantly.
> 
> I came across your comment, and I was wondering if you’ve found any solution or workaround for this problem? Any advice would be greatly appreciated. Thank you in advance for your time and help!

Hi! Yes, there is a workaround.
You basically need to make 2 containers: outer container - not scrollable and inner container - scrollable.

    <div className="outer_container">
      <div className="inner_container">
        ... your content goes here

**Comment by Rubbelg** [comment]
Why did you **close** the issues data, it won't be fixed? Since when opening the keyboard on an **iPhone**, this bug really bothers users.
