### ISSUE TITLE
[Bug]: backButton doesn't call callback on clicking

### ISSUE THREAD

**Issue by JinNguyen96** [Telegram-Mini-Apps/telegram-apps#501]
### Telegram Application

Telegram for iOS, Telegram for macOS

### Describe the Bug

I'm using @telegram-apps/sdk 2.4.0 for developing mini app with Nextjs 14. 
After mounting `backButton` and set callback for `onClick` event, tapping on the button does trigger the event but the callback isn't called

Devices tested:

Iphone 15pro - BUG
Macbook M3 Pro - BUG

### To Reproduce

1. set up code like this 
```
...
import {  backButton  } from "@telegram-apps/sdk"
...
useEffect(() => {
  backButton.mount()
  const offClick = backButton.onClick(() => console.log('clicked'))

  return () => {
    offClick()
  }
}, [])
```
2. Click back button on mini app
3. `back_button_pressed` event is triggered: `[Telegram.WebView] < receiveEvent back_button_pressed null` without `clicked` text

### Expected Behavior

callback should be called and log `clicked` once the back button is clicked

**Comment by heyqbnk** [comment]
If you see this output:
```
[Telegram.WebView] < receiveEvent back_button_pressed null
```

It means, you are using the Telegram SDK also. Remove the `telegram-web-app.js` file, as it is not compatible with `@telegram-apps/sdk`

**Comment by wufd** [comment]
#567
