### ISSUE TITLE
[Bug]: miniApp.mount() throws an error if version is not enough to change some of the colors

### ISSUE THREAD

**Issue by iuriiiurevich** [Telegram-Mini-Apps/telegram-apps#503]
### Telegram Application

Telegram for Android, Telegram for iOS, Telegram for macOS, Telegram Desktop, Telegram Web A, Telegram Web K

### Describe the Bug

For example, if you call `miniApp.mount()` in Telegram version 7.2, the following error will be thrown:

> Method "web_app_set_bottom_bar_color" is unsupported in Mini Apps version 7.2

### To Reproduce

1. Add `miniApp.mount()` to any miniapp that uses `@telegram-apps` v2
2. Open the miniapp in Telegram version < 7.10 (or mock such version)
3. See "unsupported" error

### Expected Behavior

No error :)

**Comment by heyqbnk** [comment]
Working on the solution

**Comment by heyqbnk** [comment]
Should be fine in 2.5.0

**Comment by heyqbnk** [comment]
Thank you for attention! Try 2.5.1
