### ISSUE TITLE
Eslint compains on initialising eruda in react-sdk 2.x template 

### ISSUE THREAD

**Issue by Neiz-Kap** [Telegram-Mini-Apps/telegram-apps#518]
My eslint complains on these 3 lines 

https://github.com/Telegram-Mini-Apps/telegram-apps/blob/c57d93c474d2d0b2861d1bb3ab99f24957af15cd/playgrounds/react/src/init.ts#L37

Error message: `Expected an assignment or function call and instead saw an expression.eslint[@typescript-eslint/no-unused-expressions](https://typescript-eslint.io/rules/no-unused-expressions)`

Full code:
```ts
debug && import('eruda')
    .then((lib) => lib.default.init())
    .catch(console.error);
```

Suggestion to do:
```ts
if (debug) {
  (async () => {
    try {
      const lib = await import('eruda');
      lib.default.init();
    } catch (error) {
      console.error(error);
    }
  })();
}
```

**Comment by heyqbnk** [comment]
You can ignore these warnings as long as playgrounds are just for test purposes.

Also, I don't have this issue:
<img width="371" alt="image" src="https://github.com/user-attachments/assets/b4850b43-dc78-4313-93ad-a3b0e2d4bb11">

There are also no similar warnings running the command:
```bash
eslint playgrounds/react/src/**/*
```
