### ISSUE TITLE
[Bug]: the start app launch is not working in desktop and webapp 

### ISSUE THREAD

**Issue by Trymbakmahant** [Telegram-Mini-Apps/telegram-apps#520]
### Telegram Application

Telegram Desktop, Telegram Web A

### Describe the Bug

https://t.me/botusername/appname?startapp=ABC

I am trying to implement this in my app and it's not starting the app  by just following the link 

instead of this 

https://t.me/botusername?startapp=ABC

this link is working fine for only in mobile 
on

### Expected Behavior

It should launch the app when you click on the link you

**Comment by heyqbnk** [comment]
Have you created the app for the bot? It opens fine for me.

Links for bots, using the start parameter must include the `start` query parameter, not `startapp`
