### ISSUE TITLE
[Bug]: Module "@telegram-apps/sdk-react" has no exported member "SDKProvider". ts(2305)

### ISSUE THREAD

**Issue by Pp-Tomo** [Telegram-Mini-Apps/telegram-apps#524]
### Telegram Application

Telegram for iOS, Telegram for macOS

### Describe the Bug

# package.json

  "dependencies": {
    "@next/third-parties": "^15.0.1",
    "@nextui-org/react": "^2.4.1",
    "@nextui-org/theme": "2.2.4",
    "@tanstack/react-query": "^5.40.0",
    "@telegram-apps/sdk-react": "^2.0.9",
    "axios": "^1.7.2",
    "bignumber.js": "^9.1.2",
    "clsx": "^2.1.1",
    "framer-motion": "^11.1.1",
    "jotai": "^2.10.1",
    "moment": "^2.30.1",
    "next": "14.2.3",
    "next-themes": "^0.2.1",
    "react": "18.3.1",
    "react-copy-to-clipboard": "^5.1.0",
    "react-dom": "18.3.1",
    "react-photo-view": "^1.2.6",
    "sonner": "^1.5.0",
    "tailwindcss": "3.4.3",
    "vconsole": "^3.15.1"
  },

### To Reproduce

```ts
import {  SDKProvider } from '@telegram-apps/sdk-react'
// ^ Module "@telegram-apps/sdk-react" has no exported member "SDKProvider". ts(2305)
```

### Expected Behavior

Why?

**Comment by heyqbnk** [comment]
Because it has no SDKProvider. Read documentation

**Comment by heyqbnk** [comment]
You are using another version

https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk-react/2-x
