### ISSUE TITLE
[Bug]: "Method: web_app_set_bottom_bar_color not supported"

### ISSUE THREAD

**Issue by vaughn-xyz** [Telegram-Mini-Apps/telegram-apps#528]
### Telegram Application

Other

### Describe the Bug

Using the latest `@telegram-apps/sdk-react` when we call `init()` for our Telegram mini-app this causes older/outdated Telegram clients (Web, Mobile) to crash.

My suspicion is under the hood of that `init()` call [source](https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/2-x/initializing) it must be attempting to set some default functionalities without wrapping those calls in safety `try/catch` or using the appropriate `X.isSupported()` calls internally.

We are able to fix this by wrapping the `init()` call in a `try/catch` as we noticed that this error was still bubbling up even after wrapping our own theme sets in ` try/catch`

```
try {
        console.info('[TG::App] Attempting to apply theme');
        const barColor: RGB = '#000000';
        if (app.setHeaderColor.isSupported()) {
          app.setHeaderColor(barColor);
        }
  
        if (app.setBackgroundColor.isSupported()) {
          app.setBackgroundColor(barColor);
        }
  
        // TODO investigate why this breaks
        if (app.setBottomBarColor.isSupported()) {
          app.setBottomBarColor(barColor);
        }
      } catch (error: any) {
        console.error('[TG::App] Theme error', error?.message || 'unknown');
      }
      ```

### Expected Behavior

We can safely call `init()` without having to wrap it in a `try/catch`

**Comment by heyqbnk** [comment]
You are not wrapping the `init()` function in try/catch in your code example

**Comment by tang123qi** [comment]
my code does not use related methods: web_app_set_bottom_bar_color also reports an error; how to solve this?

**Comment by vaughn-xyz** [comment]
@tang123qi I discovered this is called within the `init()` or miniApp initialize function.

To fix this for my project I had to wrap the unit call with try/catch
