### ISSUE TITLE
[Bug]: Web App not rendering the page

### ISSUE THREAD

**Issue by muhammaddiyor0104** [Telegram-Mini-Apps/telegram-apps#533]
### Telegram Application

Telegram for macOS

### Describe the Bug

i create react app using template, created a bot and added my app url using ngrok but when i open it it shows just a blank page, i tried to render my own components in render nethod but it also didn't work and i am not getting any errors, just a blank page

### To Reproduce

-

### Expected Behavior

-

**Comment by heyqbnk** [comment]
Any reproducible example? Standard template works fine for me even using ngrok
