### ISSUE TITLE
[Bug]: Error with openInvoice

### ISSUE THREAD

**Issue by tlbvkhamzin** [Telegram-Mini-Apps/telegram-apps#534]
### Telegram Application

Telegram for macOS

### Describe the Bug

Whenever I complete a TG Stars payment, I receive a following error:

```
TypeError: undefined is not an object (evaluating 'window.TelegramGameProxy.receiveEvent')
```

I am testing that on the MacOS, and indeed `TelegramGameProxy` seems not to have been defined in TG for MacOS:

<img width="198" alt="image" src="https://github.com/user-attachments/assets/4ebe70d6-be10-4b63-8d4c-3924a61fdc44">

### To Reproduce

This snippet works well on mobile, but fails on macOS:

```typescript
// ...
const status = await openInvoice(invoice_url, 'url');
if (status === 'paid') {
  alert('Successfully paid.');
}
// ...
```

### Expected Behavior

Payment notification shouldn't throw an error

**Comment by heyqbnk** [comment]
You forgot to initialize the SDK.

https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/2-x/initializing

**Comment by tlbvkhamzin** [comment]
Hi @heyqbnk. I'm doing the following on the app start:

```typescript
import { init } from '@telegram-apps/sdk-react';

// ...
init();
// ...
```

Without the initialization, it indeed didn't work on any device. But like the above it works well on iOS for example, and breaks on macOS.

Let me create a minimal reproducible case and share it with you.

**Comment by tlbvkhamzin** [comment]
Sorry, you were right. I was only initializing the app for mobile devices.
