### ISSUE TITLE
After upgrade from 1.x to 2.5.2 cloudStorage stopped working.

### ISSUE THREAD

**Issue by CodingFu** [Telegram-Mini-Apps/telegram-apps#535]
## Platform

Select platforms where this bug is reproducible:

[//]: # (To make as selected, use [x] instead of [ ].)

- [ ] Telegram for Android
- [x] Telegram for iOS
- [x] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

## Describe the bug

We used to rely on cloudStorage in v1.x of @telegram-apps/sdk

After upgrading to v2 it claims it's not supported even though telegram mini app version from `retrieveLaunchParams()` says we are at `7.10`

## To Reproduce
```js
import { init, retrieveLaunchParams, cloudStorage } from "@telegram-apps/sdk-react" 

init()
console.log(retrieveLaunchParams()) // will report version 7.10
cloudStorage.setItem('foo', 'bar') // will throw Error: ERR_NOT_SUPPORTED

```
## Expected behavior

Cloud storage should be supported (it worked just fine before we upgraded to v2)

**Comment by heyqbnk** [comment]
1. Check if you have not installed `@telegram-apps/sdk` and `@telegram-apps/sdk-react` simultaneously
2. Try logging the Mini Apps version right after calling the `init` function:
```ts
import { init, $version, cloudStorage } from "@telegram-apps/sdk-react" 

init();
console.log($version());
cloudStorage.setItem('foo', 'bar');
```
