### ISSUE TITLE
[Bug]: Issues with Cloud Storage Initialization and Sticker Customization in Telegram SDK v2.5 latest

### ISSUE THREAD

**Issue by wirapratamaz** [Telegram-Mini-Apps/telegram-apps#536]
### Telegram Application

Telegram for Android, Telegram Desktop, Other

### Describe the Bug

I am encountering two significant issues while working with the Telegram SDK v2.5:

1. **Cloud Storage Initialization**: The documentation does not provide sufficient guidance on how to initialize cloud storage. This feature is essential for managing files efficiently, but without clear instructions, it’s challenging to implement.
https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/2-x/components/cloud-storage

2. **Sticker Position Customization in Stories**: I am unable to find the functions or methods necessary to customize the position of stickers in Telegram stories. In the previous version of the SDK, this was a straightforward process, but it seems to be lacking in v2.5, making it difficult to create engaging stories.

### To Reproduce

1. **Download and Set Up**: Download the latest version of the Telegram SDK v2.5 and set it up in your development environment.
2. **Check Documentation**: Navigate to the official documentation to find information on initializing cloud storage. You will notice a lack of specific instructions or examples.
3. **Look for Sticker Customization Methods**: Search through the SDK for any functions related to sticker customization in stories. Despite thorough searching, no relevant functions are found.
4. **Attempt to Implement**: Try to implement cloud storage initialization and sticker customization based on the limited information available, leading to failure and confus

### Expected Behavior

I expected the documentation to include:
- A clear and detailed section on how to initialize cloud storage, including code examples and prerequisites.
- Specific functions or APIs for customizing sticker positions in stories, similar to what was available in the previous SDK version.

**Comment by heyqbnk** [comment]
Initialize the package.

https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/2-x/initializing
