### ISSUE TITLE
[Bug]: Use @telegram-apps/sdk-react leads to close Telegram

### ISSUE THREAD

**Issue by denisKuchko94** [Telegram-Mini-Apps/telegram-apps#547]
### Telegram Application

Telegram for macOS

### Describe the Bug

Develop tap game using Bot and 
   next.js 14 version , 
  "@telegram-apps/sdk": "^1.1.3",
   "@telegram-apps/sdk-react": "^1.1.3"

    Telegram version 11.3.1.269213 Stable, MacOs.
    
    import { initUtils } from '@telegram-apps/sdk-react';

I click on a button that triggers the utils.shareURL([referralLink](https://t.me/BotName?start=...), 'test')  method. 

<img width="370" alt="Снимок экрана 2024-11-15 в 15 40 42" src="https://github.com/user-attachments/assets/52375185-a3b1-4eff-89e9-6793c3443799">
A popup in the Telegram application opens, allowing me to select users to share the link with. After about a second, the Telegram app completely closes with the following message:
<img width="270" alt="Снимок экрана 2024-11-15 в 15 40 47" src="https://github.com/user-attachments/assets/a421fe61-cd87-4b0b-9932-2014353f9e39">

On modile device it works properly, and on MacOs with telegram version 10.2.4.255298

### Expected Behavior

Allow to share URL, using telegram popap   without closing telegram app

**Comment by heyqbnk** [comment]
I am not accepting bugs related to SDK@1.0. Please, switch to the second version and try the functionality you use
