### ISSUE TITLE
[Bug]: A Failure in the visibility of the Back button

### ISSUE THREAD

**Issue by dmitrydrynov** [Telegram-Mini-Apps/telegram-apps#554]
### Telegram Application

Telegram for Android, Telegram Desktop

### Describe the Bug

The `backButton.hide()` function does not hide the button

### To Reproduce

1. Go to 'Page 1' where I use back Button.show() for showing the button
2. Click on 'Back Button' for return on the previous page
3. On the previous page I'm using `backButton.hide()` for hidding the button but this function doesn't work. I'm seeing the button.

I can hide the back button with telegram-web-app.js
`Telegram.Web App.Back Button.show()` - I say show me the button
`Telegram.Web App.Back Button.hide()` - and now the button is hide.

### Expected Behavior

backButton.hide() should hide the button

**Comment by heyqbnk** [comment]
Please, provide the issue reproduction example
