### ISSUE TITLE
[Bug]: The openLink method is unable to open external browsers on Xiaomi phones.

### ISSUE THREAD

**Issue by Eacolt** [Telegram-Mini-Apps/telegram-apps#557]
### Telegram Application

Telegram for Android

### Describe the Bug

I am using @telegram-apps/sdk to develop a Telegram mini app on my H5 page. However, the behavior of openLink is inconsistent on Android and iOS phones. On iOS, calling openLink opens the external browser Safari, but on Android phones, calling openLink does not open the external default browser! Why is this happening, please help me! Below is the code for calling openLink:
`import {
  init,
  TelegramWebApps,
  isMiniAppSupported,
  shareURL,
  retrieveLaunchParams,
  openLink,
  openTelegramLink,
} from "@telegram-apps/sdk";`

// Unable to open external links on Android phones.

openLink("https://....", {
tryInstantView:false
}

### To Reproduce

1. Open the Telegram app on your Android phone.
2. Launch my Telegram mini app.
3. Tap the button to invoke the openLink method.
4. Instead of opening the external link, the link opens within the current Telegram interface.

### Expected Behavior

I want to use openLink in Telegram on Xiaomi's Android devices to open external browsers instead of the internal browser.

**Comment by heyqbnk** [comment]
The iOS version of Telegram has a setting in the "Data and Storage" section related to the browser to be chosen for the link.

Surely, there is something like that in Android.
