### ISSUE TITLE
[Feature]: get link

### ISSUE THREAD

**Issue by clytzeLo** [Telegram-Mini-Apps/telegram-apps#563]
### Is your feature request related to a problem? Please describe.

The Telegram mini app 8.0 has been released. I want to use the new onEvent list, such as activated and deactivated, by introducing Telegram features through https://telegram.org/js/telegram-web-app.js?2, but the new features are not taking effect during testing. I would like to inquire how to obtain the latest Telegram mini app introduction link. Meanwhile, the version output in the console is still 6.0.

### Describe the solution you'd like

I want to get the introduction link for the latest version of the Telegram mini app.

**Comment by yepCing** [comment]
i have same question 
onEvent("safeAreaChanged", change) not work

**Comment by yepCing** [comment]
i fixed it  , don't do it along with the @telegram-apps/sdk-react

**Comment by clytzeLo** [comment]
> i have same question onEvent("safeAreaChanged", change) not work

I solved it. Introduce https://telegram.org/js/telegram-web-app.js?1234, using 1234 as a new value to get the latest version. The Telegram app on the phone also needs to be updated to the latest version. If developing locally, it needs to be re-enabled.

**Comment by yepCing** [comment]
> > i have same question onEvent("safeAreaChanged", change) not work
> 
> I solved it. Introduce https://telegram.org/js/telegram-web-app.js?1234, using 1234 as a new value to get the latest version. The Telegram app on the phone also needs to be updated to the latest version. If developing locally, it needs to be re-enabled.

thanks ,i solved it too ,  I found that I introduced both js and sdk at the same time, which caused it not to work

**Comment by heyqbnk** [comment]
Not related to the repo
