### ISSUE TITLE
[Feature]: save image or video to photos album

### ISSUE THREAD

**Issue by xunjianxiang** [Telegram-Mini-Apps/telegram-apps#565]
### Is your feature request related to a problem? Please describe.

I have a web app, it helps user to get beautiful images or videos from anywhere, but i can't save them to my phone in my web app.

### Describe the solution you'd like

two apis:
- saveImageToPhotosAlbum
- saveImageToPhotosAlbum

**Comment by heyqbnk** [comment]
Will be implemented in v8.0

https://github.com/Telegram-Mini-Apps/telegram-apps/issues/553
