### ISSUE TITLE
[Feature]: Make WebApp accessible through sdk

### ISSUE THREAD

**Issue by bucurdavid** [Telegram-Mini-Apps/telegram-apps#569]
### Is your feature request related to a problem? Please describe.

The current SDK lacks support for Bot API 8.0, which limits access to new Telegram features. While waiting for an updated SDK, developers could implement a temporary workaround by using existing bridge methods and WebApp access to overcome this limitation. 
Once the updated SDK is released, the workaround/custom implementation can be easily replaced with the released implementation.
This would help devs ship fast and still leverage the power of this SDK.

### Describe the solution you'd like

Access to WebApp object from the SDK.

### Describe alternatives you've considered

An alternative considered was to drop the use of the SDK entirely and build custom solutions from scratch to leverage new features as they become available. However, this approach sacrifices the benefits and stability provided by the SDK.

**Comment by vezhdelit** [comment]
Agree. This is really needed. 

My colleagues and I were already thinking about dropping the usage of telegram-apps packages. We're worried about lacking support for Bot API 8.0 and we are not sure when it will appear at all. 

This solution would cover all our needs and problems.

**Comment by Selithrarion** [comment]
yeaaa please, would be cool

**Comment by heyqbnk** [comment]
I don't understand what is required to be done. What do you mean by "give access to WebApp"? It is the entity from a different SDK

**Comment by bucurdavid** [comment]
I was thinking of some way/method in which we could have access to the underlying WebApp object from telegram. This way we can access it and use it when new features are not available through the SDK.
What I mean by WebApp object is window.Telegram.WebApp. 

Because when using the sdk, the WebApp is not exposed in window.

**Comment by heyqbnk** [comment]
There is no such thing as "underlying WebApp" object. This SDK is not connected with the `telegram-web-app.js` file, it doesn't use and enhance it. They are 2 totally separate libraries.

The WebApp object is defined by the `telegram-web-app.js` file
