### ISSUE TITLE
[Bug]: Typescript errors related to the library's types

### ISSUE THREAD

**Issue by RickCastle2018** [Telegram-Mini-Apps/telegram-apps#570]
### Telegram Application

Other

### Describe the Bug

<img width="555" alt="image" src="https://github.com/user-attachments/assets/59405c6d-5868-46ac-b2af-b7fff7746f1a">

Couldn't get rid of these errors no matter what in VSCode.

### To Reproduce

1. Use the library with Vite, I guess

### Expected Behavior

No errors.

**Comment by heyqbnk** [comment]
Seems like you forgot to exclude the `node_modules` directory from indexing
