### ISSUE TITLE
[Bug]: shareStory does not work on iOS

### ISSUE THREAD

**Issue by emperor1412** [Telegram-Mini-Apps/telegram-apps#586]
### Telegram Application

Telegram for iOS

### Describe the Bug

ShareStory functionalities doesn't work on iOS but Android.

sdk version:
"@telegram-apps/sdk": "^2.9.0",

Telegram mini app version: 8.0

### To Reproduce

Use this simple code to test on iOS device:

```
import { shareStory } from '@telegram-apps/sdk';

if (shareStory.isAvailable()) {
    try {
        shareStory('https://pub-8bab4a9dfe21470ebad9203e437e2292.r2.dev/miniGameHub/hHinjx/xY6gECBXlMiE1Z95dGmuh/3Pqzg/tEcJ1P3s=');
    }
    catch (e) {
        console.log('Error sharing the story:', e);
    }
}
```

When shareStory is called, the iOS telegram mini app will get stuck on the loading icon, the only way to get out of the stuck is to kill the telegram app.

### Expected Behavior

It should lead to the Story Editor view on native telegram app

**Comment by heyqbnk** [comment]
This code works fine for me:

```ts
import { init, shareStory } from '@telegram-apps/sdk';

init();
shareStory('https://placehold.co/192x192/png');
```

You link has an incorrect mime type, maybe it is the reason.

**Comment by emperor1412** [comment]
> This code works fine for me:
> 
> ```ts
> import { init, shareStory } from '@telegram-apps/sdk';
> 
> init();
> shareStory('https://placehold.co/192x192/png');
> ```
> 
> You link has an incorrect mime type, maybe it is the reason.

thank you, it's working now, although it's like a bizarre thing to me, it's strange they don't mention this in any documentation.
