### ISSUE TITLE
[Bug]: "initData" transformer failed to parse the value in Nuxt 3 application

### ISSUE THREAD

**Issue by AlanTheKnight** [Telegram-Mini-Apps/telegram-apps#592]
### Telegram Application

Other

### Describe the Bug

It is a known bug that there are sometimes troubles with parsing the launch parameters in Vue Router. Nuxt 3 also uses Vue Router under the hood, so I followed the documentation and changed Vue Router history mode to `HTML5` mode (via `createWebHistory`). In Nuxt 3, it's done like this (also following [their documentation](https://nuxt.com/docs/guide/recipes/custom-routing#custom-history-advanced)):

`app/router.options.ts`

```ts
import { createWebHistory } from '#vue-router';
import type { RouterConfig } from '@nuxt/schema';

export default {
  // https://router.vuejs.org/api/interfaces/routeroptions.html#routes
  history: (base) => (import.meta.client ? createWebHistory(base) : null)
} satisfies RouterConfig;
```

I have initialized the library via Nuxt client plugin:

`plugins/telegram.ts`:

```ts
import { init, isTMA } from '@telegram-apps/sdk-vue';

export default defineNuxtPlugin((app) => {
  if (isTMA('simple')) {
    init();
  }
});
```

In my `app.vue`, I want to retrieve init data from Telegram:

```vue
<script lang="ts" setup>

... Some code ...

onMounted(() => {
  if (isTMA('simple')) {
    mountMiniApp();
    setMiniAppBackgroundColor('#121212');
    setMiniAppHeaderColor('#212121');
    miniAppReady();
  }

  const hash = window.location.hash.slice(1);
  console.log('hash', hash);

  const initData = isTMA('simple') ? parseInitData() : undefined;
});

... Some code ...

</script>
```

However, once the application is run inside Telegram, I get an error:

```
[nuxt] error caught during app initialization _H: "initData" transformer failed to parse the value
    at r (https://cambridge-e-package-reform.trycloudflare.com/_nuxt/node_modules/.cache/vite/client/deps/@telegram-apps_sdk-vue.js?v=cebec228:65:17)
    at Wc (https://cambridge-e-package-reform.trycloudflare.com/_nuxt/node_modules/.cache/vite/client/deps/@telegram-apps_sdk-vue.js?v=cebec228:1814:14)
    
    ... Long error stacktrace
```

As for the `window.location.hash.slice(1)` value, it gives:

```
tgWebAppData=query_id=AAGOZ6w6AwAAAI5nrDp7yMEI&user={%22id%22:7426828174,%22first_name%22:%22Maksim%22,%22last_name%22:%22G%22,%22username%22:%22atkgus%22,%22language_code%22:%22en%22,%22allows_write_to_pm%22:true,%22photo_url%22:%22https:%5C/%5C/t.me%5C/i%5C/userpic%5C/320%5C/HSdpLuQAsdHfP4SWtzZBUgJz8sNh9hgRUY14QWvBMWtFqIWRoeoj2-DO6nNBIWMh.svg%22}&auth_date=1733855896&signature=NnUHmKoh4PDfqIG7-sdfVf_LyNemW1_G86ix8pujgE3pn8lLeYUZUMYB7_nRcYfJjWRjrX4-uA6QwAKA8THIBw&hash=d25386eb95f82ba5d0717d93741273c123c59c20fe99fdaf7773ab653a2e800e&tgWebAppVersion=8.0&tgWebAppPlatform=android&tgWebAppThemeParams={%22bg_color%22:%22#1e1e1e%22,%22section_bg_color%22:%22#191818%22,%22secondary_bg_color%22:%22#000000%22,%22text_color%22:%22#ffffff%22,%22hint_color%22:%22#7d7d7d%22,%22link_color%22:%22#e65b5b%22,%22button_color%22:%22#f55555%22,%22button_text_color%22:%22#ffffff%22,%22header_bg_color%22:%22#252422%22,%22accent_text_color%22:%22#f26767%22,%22section_header_text_color%22:%22#f76d6d%22,%22subtitle_text_color%22:%22#7e7e7d%22,%22destructive_text_color%22:%22#ee686f%22,%22section_separator_color%22:%22#000000%22,%22bottom_bar_bg_color%22:%22#000000%22}
```

Also, there's a warning in console that is related to the issue as well:

```
[Vue Router warn]: The selector "#tgWebAppData=query_id=AAGOZ6w6AwAAAI5nrDp7yMEI&user={"id":7426828174,"first_name":"Maksim","last_name":"G","username":"atkgus","language_code":"en","allows_write_to_pm":true,"photo_url":"https:\/\/t.me\/i\/userpic\/320\/HSdpLuQAsdHfP4SWtzZBUgJz8sNh9hgRUY14QWvBMWtFqIWRoeoj2-DO6nNBIWMh.svg"}&auth_date=1733855896&signature=NnUHmKoh4PDfqIG7-sdfVf_LyNemW1_G86ix8pujgE3pn8lLeYUZUMYB7_nRcYfJjWRjrX4-uA6QwAKA8THIBw&hash=d25386eb95f82ba5d0717d93741273c123c59c20fe99fdaf7773ab653a2e800e&tgWebAppVersion=8.0&tgWebAppPlatform=android&tgWebAppThemeParams={"bg_color":"#1e1e1e","section_bg_color":"#191818","secondary_bg_color":"#000000","text_color":"#ffffff","hint_color":"#7d7d7d","link_color":"#e65b5b","button_color":"#f55555","button_text_color":"#ffffff","header_bg_color":"#252422","accent_text_color":"#f26767","section_header_text_color":"#f76d6d","subtitle_text_color":"#7e7e7d","destructive_text_color":"#ee686f","section_separator_color":"#000000","bottom_bar_bg_color":"#000000"}" is invalid. If you are using an id selector, make sure to escape it. You can find more information about escaping characters in selectors at https://mathiasbynens.be/notes/css-escapes or use CSS.escape (https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape).
```

I am trying to transition my project to this library instead of [`vue-tg`](https://github.com/deptyped/vue-telegram). When I was using it, there's been a similar issue, however, I fixed it [by following this guy's advice](https://github.com/deptyped/vue-telegram/issues/18#issuecomment-2121750340). As well as here no script is used, I am a bit confused of what do I exactly need to do.

What can I do to address the issue?

### To Reproduce

- Try to call `parseInitData` in a Nuxt 3 project with configuration I provided above

### Expected Behavior

- initData parsing correctly

**Comment by dnischeta** [comment]
I'll take a look on that one today.

**Comment by glebshkut** [comment]
Same in Next.js React @dnischeta 
```"initData" transformer failed to parse the value```

**Comment by dnischeta** [comment]
@AlanTheKnight , which version of `@telegram-apps/sdk-vue` do you use?
Try to downgrade to `1.0.9` as a temporary solution, looks like it helps 🤔

**Comment by dnischeta** [comment]
About that one.

> Also, there's a warning in console that is related to the issue as well:
> [Vue Router warn]: The selector "#tgWebAppData=..." is invalid. If you are using an id selector, make sure to escape it. You can find more information about escaping characters in selectors at https://mathiasbynens.be/notes/css-escapes or use CSS.escape (https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape).

It happens, because Nuxt tries to scroll to the element with ID of hash. In case of TMA it's incorrect (because hash is not a correct DOM element ID). The only way I see for now is to rewrite `scrollBehaviour` option in [router.options.ts](https://github.com/nuxt/nuxt/blob/976fda169bd253779b058b0b6702c11f18be2f1b/packages/nuxt/src/pages/runtime/router.options.ts#L4).

**Comment by dnischeta** [comment]
By the way, do you mock telegram env somehow?  And do you face that issue in dev or prod or both?

**Comment by dnischeta** [comment]
@glebshkut , you can add `signature` into `initDataRaw` inside `mockTelegram`, like that:

```ts
const initDataRaw = new URLSearchParams([
                // All other fields
                ['signature', 'aabb'],
            ]).toString();
```

And then upgrade sdk, everything should be fine.

**Comment by AlanTheKnight** [comment]
> @AlanTheKnight , which version of `@telegram-apps/sdk-vue` do you use? Try to downgrade to `1.0.9` as a temporary solution, looks like it helps 🤔
> 
> PS. It doesn't mean we close issue, just a temporary solution for you to continue migration.

I've been using the last version (`1.0.10`), however, after I've downgraded it to `1.0.9` nothing changed, the issue still persists.

**Comment by dnischeta** [comment]
Hmm, ok. Could you, please, provide more info:
- do you face that issue in dev or prod or both?
- in case you face that issue on prod, how do you serve you app (I mean is it static hosting or codesandbox or standalone server)?
- please, provide  full error screenshot or text, so we will see the root problem (like on the screenshot).

![image (22)](https://github.com/user-attachments/assets/586f51ac-eb61-4bda-a1da-96426db66ee1)

**Comment by AlanTheKnight** [comment]
True, my bad, didn't notice that. Thanks a lot for your help. I'm closing the issue.

> @AlanTheKnight Lol, shame on me. Look, you have next call: `const initData = isTMA('simple') ? parseInitData() : undefined;`. But you should do:
> 
> ```js
> const lp = retrieveLaunchParams();
> 
> const initData = isTMA('simple') ? parseInitData(lp.initDataRaw) : undefined;
> ```
> 
> At least, actual typedef says so. I'll take a look on [docs](https://docs.telegram-mini-apps.com/packages/telegram-apps-sdk/2-x/components/init-data#parsing), looks like it's outdated :(
